### ISSUE TITLE
Simplify Plugfests Folder Tree

### ISSUE THREAD

**Issue by dlemire60** [opencybersecurityalliance/casp#69]
The current organization of the folders under plugfests seems inefficient, and a strategy that guarantees links change over time creates accessibility problems.  Suggest we simply have:

- Plugfests
  - date-location
  - date-location
  - date-location
 
The details about the status of a given plugfest can be contained in its README.md file. The dates are sufficient to distinguish past / future, and this way links to pages within each plugfest remain stable.

**Comment by davaya** [comment]
Agree, and done.
